---
title       : Data Products
subtitle    : Course Project
author      : Claudia V
job         : Data scientist in training
framework   : shower      # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {selfcontained, draft}
knit        : slidify::knit2slides
---

## Twitter Data Products 
By Claudia V


--- 

## How it works
The first user you input should be your brand and the other two the competitors. 
The users should be entered as: "@brand" or "brand"

Be patience it might take a couple of minutes to load the data from TW

Each TW user you input retreives the latest 100 mentions*. 
*There might be some cases when there are not enough mentions to retreive, there are some blank tweets due to the change in RT's by Twitter. 



--- 
## Time and interactions analysis. 
I was not able to make this using the dynamic data, but I've included a sample of the analysis 
Tweets are separated to get the ones made exclusively by each brand and the number of RTs and Fav is added into interactions. 

--- 
## Sample Plots 
```{r chunk_name, echo=FALSE, message=FALSE}
library(repmis)
Brand <- repmis::source_DropboxData("sampleData.csv",
                                  "ma62f5cmcey5ht9",
                                  sep = ",",
                                  header = TRUE)
myplot<-qplot( Hour, int, data = Brand,color=screenName, geom = "point") +
  geom_point() + theme_grey(base_size = 18) +
  xlab("Hora de Publicación") +
  ylab("Total de Interacciones") +
  labs(title = "Interacciones TW ")
print(myplot)

myplot<-qplot( Hour, int, data = Brand,color=screenName, geom = "point") +
  geom_point() + theme_grey(base_size = 18) +
  xlab("Hora de Publicación") +
  ylab("Total de Interacciones") +
  labs(title = "Promedio de interacciones TW por marca por Hora")
print(myplot)


```

---
## About
This project was created for the Coursera Data Science Specialization
Shiny R Studio Tutorials
TwitterR package
http://blog.dataweave.in/post/96618078833/building-a-twitter-sentiment-analysis-app-using-r

--- 
